// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source types.go -package mocks -destination mocks/mock_types.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	guid "github.com/Microsoft/go-winio/pkg/guid"
	mount "github.com/Microsoft/hcsshim/internal/controller/device/plan9/mount"
	share "github.com/Microsoft/hcsshim/internal/controller/device/plan9/share"
	disk "github.com/Microsoft/hcsshim/internal/controller/device/scsi/disk"
	mount0 "github.com/Microsoft/hcsshim/internal/controller/device/scsi/mount"
	vpci "github.com/Microsoft/hcsshim/internal/controller/device/vpci"
	gomock "go.uber.org/mock/gomock"
)

// MockSCSIReserver is a mock of SCSIReserver interface.
type MockSCSIReserver struct {
	ctrl     *gomock.Controller
	recorder *MockSCSIReserverMockRecorder
	isgomock struct{}
}

// MockSCSIReserverMockRecorder is the mock recorder for MockSCSIReserver.
type MockSCSIReserverMockRecorder struct {
	mock *MockSCSIReserver
}

// NewMockSCSIReserver creates a new mock instance.
func NewMockSCSIReserver(ctrl *gomock.Controller) *MockSCSIReserver {
	mock := &MockSCSIReserver{ctrl: ctrl}
	mock.recorder = &MockSCSIReserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSCSIReserver) EXPECT() *MockSCSIReserverMockRecorder {
	return m.recorder
}

// Reserve mocks base method.
func (m *MockSCSIReserver) Reserve(ctx context.Context, diskConfig disk.Config, mountConfig mount0.Config) (guid.GUID, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, diskConfig, mountConfig)
	ret0, _ := ret[0].(guid.GUID)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Reserve indicates an expected call of Reserve.
func (mr *MockSCSIReserverMockRecorder) Reserve(ctx, diskConfig, mountConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockSCSIReserver)(nil).Reserve), ctx, diskConfig, mountConfig)
}

// UnmapFromGuest mocks base method.
func (m *MockSCSIReserver) UnmapFromGuest(ctx context.Context, reservation guid.GUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmapFromGuest", ctx, reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmapFromGuest indicates an expected call of UnmapFromGuest.
func (mr *MockSCSIReserverMockRecorder) UnmapFromGuest(ctx, reservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmapFromGuest", reflect.TypeOf((*MockSCSIReserver)(nil).UnmapFromGuest), ctx, reservation)
}

// MockPlan9Reserver is a mock of Plan9Reserver interface.
type MockPlan9Reserver struct {
	ctrl     *gomock.Controller
	recorder *MockPlan9ReserverMockRecorder
	isgomock struct{}
}

// MockPlan9ReserverMockRecorder is the mock recorder for MockPlan9Reserver.
type MockPlan9ReserverMockRecorder struct {
	mock *MockPlan9Reserver
}

// NewMockPlan9Reserver creates a new mock instance.
func NewMockPlan9Reserver(ctrl *gomock.Controller) *MockPlan9Reserver {
	mock := &MockPlan9Reserver{ctrl: ctrl}
	mock.recorder = &MockPlan9ReserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlan9Reserver) EXPECT() *MockPlan9ReserverMockRecorder {
	return m.recorder
}

// Reserve mocks base method.
func (m *MockPlan9Reserver) Reserve(ctx context.Context, shareConfig share.Config, mountConfig mount.Config) (guid.GUID, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, shareConfig, mountConfig)
	ret0, _ := ret[0].(guid.GUID)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Reserve indicates an expected call of Reserve.
func (mr *MockPlan9ReserverMockRecorder) Reserve(ctx, shareConfig, mountConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockPlan9Reserver)(nil).Reserve), ctx, shareConfig, mountConfig)
}

// UnmapFromGuest mocks base method.
func (m *MockPlan9Reserver) UnmapFromGuest(ctx context.Context, reservation guid.GUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmapFromGuest", ctx, reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmapFromGuest indicates an expected call of UnmapFromGuest.
func (mr *MockPlan9ReserverMockRecorder) UnmapFromGuest(ctx, reservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmapFromGuest", reflect.TypeOf((*MockPlan9Reserver)(nil).UnmapFromGuest), ctx, reservation)
}

// MockVPCIReserver is a mock of VPCIReserver interface.
type MockVPCIReserver struct {
	ctrl     *gomock.Controller
	recorder *MockVPCIReserverMockRecorder
	isgomock struct{}
}

// MockVPCIReserverMockRecorder is the mock recorder for MockVPCIReserver.
type MockVPCIReserverMockRecorder struct {
	mock *MockVPCIReserver
}

// NewMockVPCIReserver creates a new mock instance.
func NewMockVPCIReserver(ctrl *gomock.Controller) *MockVPCIReserver {
	mock := &MockVPCIReserver{ctrl: ctrl}
	mock.recorder = &MockVPCIReserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVPCIReserver) EXPECT() *MockVPCIReserverMockRecorder {
	return m.recorder
}

// RemoveFromVM mocks base method.
func (m *MockVPCIReserver) RemoveFromVM(ctx context.Context, vmBusGUID guid.GUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromVM", ctx, vmBusGUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromVM indicates an expected call of RemoveFromVM.
func (mr *MockVPCIReserverMockRecorder) RemoveFromVM(ctx, vmBusGUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromVM", reflect.TypeOf((*MockVPCIReserver)(nil).RemoveFromVM), ctx, vmBusGUID)
}

// Reserve mocks base method.
func (m *MockVPCIReserver) Reserve(ctx context.Context, device vpci.Device) (guid.GUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, device)
	ret0, _ := ret[0].(guid.GUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockVPCIReserverMockRecorder) Reserve(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockVPCIReserver)(nil).Reserve), ctx, device)
}
