// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: github.com/Microsoft/hcsshim/internal/lm/proto/lm.proto

package lmproto

import (
	types "github.com/containerd/containerd/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferSandboxResponse_Status int32

const (
	TransferSandboxResponse_STATUS_UNSPECIFIED          TransferSandboxResponse_Status = 0
	TransferSandboxResponse_STATUS_BROWNOUT_IN_PROGRESS TransferSandboxResponse_Status = 1
	TransferSandboxResponse_STATUS_BLACKOUT_IN_PROGRESS TransferSandboxResponse_Status = 2
	TransferSandboxResponse_STATUS_COMPLETE             TransferSandboxResponse_Status = 3
	TransferSandboxResponse_STATUS_FAILED               TransferSandboxResponse_Status = 4
	TransferSandboxResponse_STATUS_CANCEL               TransferSandboxResponse_Status = 5
)

// Enum value maps for TransferSandboxResponse_Status.
var (
	TransferSandboxResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_BROWNOUT_IN_PROGRESS",
		2: "STATUS_BLACKOUT_IN_PROGRESS",
		3: "STATUS_COMPLETE",
		4: "STATUS_FAILED",
		5: "STATUS_CANCEL",
	}
	TransferSandboxResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":          0,
		"STATUS_BROWNOUT_IN_PROGRESS": 1,
		"STATUS_BLACKOUT_IN_PROGRESS": 2,
		"STATUS_COMPLETE":             3,
		"STATUS_FAILED":               4,
		"STATUS_CANCEL":               5,
	}
)

func (x TransferSandboxResponse_Status) Enum() *TransferSandboxResponse_Status {
	p := new(TransferSandboxResponse_Status)
	*p = x
	return p
}

func (x TransferSandboxResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferSandboxResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_enumTypes[0].Descriptor()
}

func (TransferSandboxResponse_Status) Type() protoreflect.EnumType {
	return &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_enumTypes[0]
}

func (x TransferSandboxResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferSandboxResponse_Status.Descriptor instead.
func (TransferSandboxResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{15, 0}
}

type FinalizeSandboxRequest_Action int32

const (
	FinalizeSandboxRequest_ACTION_UNSPECIFIED FinalizeSandboxRequest_Action = 0
	FinalizeSandboxRequest_ACTION_STOP        FinalizeSandboxRequest_Action = 1
	FinalizeSandboxRequest_ACTION_RESUME      FinalizeSandboxRequest_Action = 2
)

// Enum value maps for FinalizeSandboxRequest_Action.
var (
	FinalizeSandboxRequest_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_STOP",
		2: "ACTION_RESUME",
	}
	FinalizeSandboxRequest_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_STOP":        1,
		"ACTION_RESUME":      2,
	}
)

func (x FinalizeSandboxRequest_Action) Enum() *FinalizeSandboxRequest_Action {
	p := new(FinalizeSandboxRequest_Action)
	*p = x
	return p
}

func (x FinalizeSandboxRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalizeSandboxRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_enumTypes[1].Descriptor()
}

func (FinalizeSandboxRequest_Action) Type() protoreflect.EnumType {
	return &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_enumTypes[1]
}

func (x FinalizeSandboxRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalizeSandboxRequest_Action.Descriptor instead.
func (FinalizeSandboxRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{18, 0}
}

// This type should be binary-protobuf serialized and put in config.binpb in the sandbox's bundle.
type SandboxLMSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The same config that was returned via PrepareSandboxResponse.
	Config *anypb.Any `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// The new network namespace to use for the sandbox.
	Netns string `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	// Adjusted resources (only rootfs supported for now).
	Resources   *DestinationResources `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Annotations map[string]string     `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SandboxLMSpec) Reset() {
	*x = SandboxLMSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxLMSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxLMSpec) ProtoMessage() {}

func (x *SandboxLMSpec) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxLMSpec.ProtoReflect.Descriptor instead.
func (*SandboxLMSpec) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxLMSpec) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SandboxLMSpec) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *SandboxLMSpec) GetResources() *DestinationResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SandboxLMSpec) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type DestinationResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskRootfs []*DestinationRootFS `protobuf:"bytes,1,rep,name=task_rootfs,json=taskRootfs,proto3" json:"task_rootfs,omitempty"`
}

func (x *DestinationResources) Reset() {
	*x = DestinationResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestinationResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationResources) ProtoMessage() {}

func (x *DestinationResources) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationResources.ProtoReflect.Descriptor instead.
func (*DestinationResources) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{1}
}

func (x *DestinationResources) GetTaskRootfs() []*DestinationRootFS {
	if x != nil {
		return x.TaskRootfs
	}
	return nil
}

type DestinationRootFS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the resource, acts as a unique key.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The new mount that should be used to replace the task's rootfs.
	Rootfs *types.Mount `protobuf:"bytes,2,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
}

func (x *DestinationRootFS) Reset() {
	*x = DestinationRootFS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestinationRootFS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationRootFS) ProtoMessage() {}

func (x *DestinationRootFS) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationRootFS.ProtoReflect.Descriptor instead.
func (*DestinationRootFS) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{2}
}

func (x *DestinationRootFS) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DestinationRootFS) GetRootfs() *types.Mount {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

// This type should be binary-protobuf serialized and put in config.binpb in the container's bundle.
type ContainerRestoreSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The original container's ID that should be "restored" as this new container.
	OriginalId  string            `protobuf:"bytes,1,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`
	Annotations map[string]string `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ContainerRestoreSpec) Reset() {
	*x = ContainerRestoreSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerRestoreSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRestoreSpec) ProtoMessage() {}

func (x *ContainerRestoreSpec) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRestoreSpec.ProtoReflect.Descriptor instead.
func (*ContainerRestoreSpec) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerRestoreSpec) GetOriginalId() string {
	if x != nil {
		return x.OriginalId
	}
	return ""
}

func (x *ContainerRestoreSpec) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type PrepareSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PrepareSandboxRequest) Reset() {
	*x = PrepareSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSandboxRequest) ProtoMessage() {}

func (x *PrepareSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSandboxRequest.ProtoReflect.Descriptor instead.
func (*PrepareSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{4}
}

type PrepareSandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An opaque config that should be set in the SandboxLMSpec on the destination.
	Config *anypb.Any `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Original resources (only rootfs supported for now).
	Resources *SourceResources `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *PrepareSandboxResponse) Reset() {
	*x = PrepareSandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSandboxResponse) ProtoMessage() {}

func (x *PrepareSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSandboxResponse.ProtoReflect.Descriptor instead.
func (*PrepareSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareSandboxResponse) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PrepareSandboxResponse) GetResources() *SourceResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type SourceResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskRootfs []*SourceRootFS `protobuf:"bytes,1,rep,name=task_rootfs,json=taskRootfs,proto3" json:"task_rootfs,omitempty"`
}

func (x *SourceResources) Reset() {
	*x = SourceResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceResources) ProtoMessage() {}

func (x *SourceResources) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceResources.ProtoReflect.Descriptor instead.
func (*SourceResources) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{6}
}

func (x *SourceResources) GetTaskRootfs() []*SourceRootFS {
	if x != nil {
		return x.TaskRootfs
	}
	return nil
}

type SourceRootFS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the resource, acts as a unique key.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The task ID that this rootfs was provided for.
	TaskId string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *SourceRootFS) Reset() {
	*x = SourceRootFS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceRootFS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRootFS) ProtoMessage() {}

func (x *SourceRootFS) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRootFS.ProtoReflect.Descriptor instead.
func (*SourceRootFS) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{7}
}

func (x *SourceRootFS) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SourceRootFS) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListenChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ListenChannelRequest) Reset() {
	*x = ListenChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenChannelRequest) ProtoMessage() {}

func (x *ListenChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenChannelRequest.ProtoReflect.Descriptor instead.
func (*ListenChannelRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{8}
}

func (x *ListenChannelRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ListenChannelRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ListenChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port uint32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ListenChannelResponse) Reset() {
	*x = ListenChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenChannelResponse) ProtoMessage() {}

func (x *ListenChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenChannelResponse.ProtoReflect.Descriptor instead.
func (*ListenChannelResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{9}
}

func (x *ListenChannelResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type AcceptChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptChannelRequest) Reset() {
	*x = AcceptChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptChannelRequest) ProtoMessage() {}

func (x *AcceptChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptChannelRequest.ProtoReflect.Descriptor instead.
func (*AcceptChannelRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{10}
}

type AcceptChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptChannelResponse) Reset() {
	*x = AcceptChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptChannelResponse) ProtoMessage() {}

func (x *AcceptChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptChannelResponse.ProtoReflect.Descriptor instead.
func (*AcceptChannelResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{11}
}

type DialChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *DialChannelRequest) Reset() {
	*x = DialChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialChannelRequest) ProtoMessage() {}

func (x *DialChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialChannelRequest.ProtoReflect.Descriptor instead.
func (*DialChannelRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{12}
}

func (x *DialChannelRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DialChannelRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type DialChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DialChannelResponse) Reset() {
	*x = DialChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialChannelResponse) ProtoMessage() {}

func (x *DialChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialChannelResponse.ProtoReflect.Descriptor instead.
func (*DialChannelResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{13}
}

type TransferSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransferSandboxRequest) Reset() {
	*x = TransferSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferSandboxRequest) ProtoMessage() {}

func (x *TransferSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferSandboxRequest.ProtoReflect.Descriptor instead.
func (*TransferSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{14}
}

// Provides streaming updates on the LM transfer operation.
type TransferSandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Increments on each message. Can be used to ensure messages are not processed twice in the case of a client crash.
	MessageId    uint32                         `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status       TransferSandboxResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=runhcs.lm.TransferSandboxResponse_Status" json:"status,omitempty"`
	ErrorMessage string                         `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Between 0 and 1 (inclusive).
	Progress float32 `protobuf:"fixed32,4,opt,name=progress,proto3" json:"progress,omitempty"`
	// The time when the transfer started.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The time when this update occurred.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *TransferSandboxResponse) Reset() {
	*x = TransferSandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferSandboxResponse) ProtoMessage() {}

func (x *TransferSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferSandboxResponse.ProtoReflect.Descriptor instead.
func (*TransferSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{15}
}

func (x *TransferSandboxResponse) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *TransferSandboxResponse) GetStatus() TransferSandboxResponse_Status {
	if x != nil {
		return x.Status
	}
	return TransferSandboxResponse_STATUS_UNSPECIFIED
}

func (x *TransferSandboxResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransferSandboxResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TransferSandboxResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TransferSandboxResponse) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{16}
}

type CancelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{17}
}

type FinalizeSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The action to perform on the sandbox.
	Action FinalizeSandboxRequest_Action `protobuf:"varint,2,opt,name=action,proto3,enum=runhcs.lm.FinalizeSandboxRequest_Action" json:"action,omitempty"`
}

func (x *FinalizeSandboxRequest) Reset() {
	*x = FinalizeSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSandboxRequest) ProtoMessage() {}

func (x *FinalizeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSandboxRequest.ProtoReflect.Descriptor instead.
func (*FinalizeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{18}
}

func (x *FinalizeSandboxRequest) GetAction() FinalizeSandboxRequest_Action {
	if x != nil {
		return x.Action
	}
	return FinalizeSandboxRequest_ACTION_UNSPECIFIED
}

type FinalizeSandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinalizeSandboxResponse) Reset() {
	*x = FinalizeSandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSandboxResponse) ProtoMessage() {}

func (x *FinalizeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSandboxResponse.ProtoReflect.Descriptor instead.
func (*FinalizeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP(), []int{19}
}

var File_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto protoreflect.FileDescriptor

var file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDesc = []byte{
	0x0a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x68, 0x63, 0x73, 0x73, 0x68, 0x69, 0x6d, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6c, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6c, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x75, 0x6e, 0x68, 0x63,
	0x73, 0x2e, 0x6c, 0x6d, 0x1a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x0d, 0x53, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x4c, 0x4d, 0x53, 0x70, 0x65, 0x63, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x65, 0x74, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x65, 0x74, 0x6e, 0x73, 0x12, 0x3d,
	0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x44, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x4b, 0x0a,
	0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x53,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x4c, 0x4d, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x41, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x41, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x55, 0x0a, 0x14, 0x44, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x66,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73,
	0x2e, 0x6c, 0x6d, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x6f, 0x6f, 0x74, 0x46, 0x53, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x66,
	0x73, 0x22, 0x54, 0x0a, 0x11, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x6f, 0x6f, 0x74, 0x46, 0x53, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x74, 0x66, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49,
	0x64, 0x12, 0x52, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e,
	0x6c, 0x6d, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x80,
	0x01, 0x0a, 0x16, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e,
	0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x22, 0x4b, 0x0a, 0x0f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x72, 0x6f, 0x6f,
	0x74, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x68,
	0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x74,
	0x46, 0x53, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x52, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x22, 0x37,
	0x0a, 0x0c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x46, 0x53, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x16, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x38, 0x0a, 0x12, 0x44, 0x69, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x44,
	0x69, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd4, 0x03, 0x0a,
	0x17, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73,
	0x2e, 0x6c, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x42, 0x52, 0x4f, 0x57, 0x4e, 0x4f, 0x55, 0x54, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f,
	0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x4f, 0x55, 0x54, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52,
	0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04,
	0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45,
	0x4c, 0x10, 0x05, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x40, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x28, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x12, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x53, 0x54, 0x4f, 0x50, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x52, 0x45, 0x53, 0x55, 0x4d, 0x45, 0x10, 0x02, 0x22, 0x19, 0x0a, 0x17, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcd, 0x04, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x55, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x53, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x12, 0x20, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d,
	0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e,
	0x6c, 0x6d, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1f, 0x2e, 0x72, 0x75, 0x6e,
	0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x75,
	0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x0d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1f,
	0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x44, 0x69, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x1d, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x44, 0x69, 0x61,
	0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x44, 0x69, 0x61, 0x6c,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5a, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x12, 0x21, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c,
	0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x58, 0x0a, 0x0f, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x12, 0x21,
	0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12,
	0x18, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x75, 0x6e, 0x68,
	0x63, 0x73, 0x2e, 0x6c, 0x6d, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescOnce sync.Once
	file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescData = file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDesc
)

func file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescGZIP() []byte {
	file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescOnce.Do(func() {
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescData)
	})
	return file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDescData
}

var file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_goTypes = []interface{}{
	(TransferSandboxResponse_Status)(0), // 0: runhcs.lm.TransferSandboxResponse.Status
	(FinalizeSandboxRequest_Action)(0),  // 1: runhcs.lm.FinalizeSandboxRequest.Action
	(*SandboxLMSpec)(nil),               // 2: runhcs.lm.SandboxLMSpec
	(*DestinationResources)(nil),        // 3: runhcs.lm.DestinationResources
	(*DestinationRootFS)(nil),           // 4: runhcs.lm.DestinationRootFS
	(*ContainerRestoreSpec)(nil),        // 5: runhcs.lm.ContainerRestoreSpec
	(*PrepareSandboxRequest)(nil),       // 6: runhcs.lm.PrepareSandboxRequest
	(*PrepareSandboxResponse)(nil),      // 7: runhcs.lm.PrepareSandboxResponse
	(*SourceResources)(nil),             // 8: runhcs.lm.SourceResources
	(*SourceRootFS)(nil),                // 9: runhcs.lm.SourceRootFS
	(*ListenChannelRequest)(nil),        // 10: runhcs.lm.ListenChannelRequest
	(*ListenChannelResponse)(nil),       // 11: runhcs.lm.ListenChannelResponse
	(*AcceptChannelRequest)(nil),        // 12: runhcs.lm.AcceptChannelRequest
	(*AcceptChannelResponse)(nil),       // 13: runhcs.lm.AcceptChannelResponse
	(*DialChannelRequest)(nil),          // 14: runhcs.lm.DialChannelRequest
	(*DialChannelResponse)(nil),         // 15: runhcs.lm.DialChannelResponse
	(*TransferSandboxRequest)(nil),      // 16: runhcs.lm.TransferSandboxRequest
	(*TransferSandboxResponse)(nil),     // 17: runhcs.lm.TransferSandboxResponse
	(*CancelRequest)(nil),               // 18: runhcs.lm.CancelRequest
	(*CancelResponse)(nil),              // 19: runhcs.lm.CancelResponse
	(*FinalizeSandboxRequest)(nil),      // 20: runhcs.lm.FinalizeSandboxRequest
	(*FinalizeSandboxResponse)(nil),     // 21: runhcs.lm.FinalizeSandboxResponse
	nil,                                 // 22: runhcs.lm.SandboxLMSpec.AnnotationsEntry
	nil,                                 // 23: runhcs.lm.ContainerRestoreSpec.AnnotationsEntry
	(*anypb.Any)(nil),                   // 24: google.protobuf.Any
	(*types.Mount)(nil),                 // 25: containerd.types.Mount
	(*timestamppb.Timestamp)(nil),       // 26: google.protobuf.Timestamp
}
var file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_depIdxs = []int32{
	24, // 0: runhcs.lm.SandboxLMSpec.config:type_name -> google.protobuf.Any
	3,  // 1: runhcs.lm.SandboxLMSpec.resources:type_name -> runhcs.lm.DestinationResources
	22, // 2: runhcs.lm.SandboxLMSpec.annotations:type_name -> runhcs.lm.SandboxLMSpec.AnnotationsEntry
	4,  // 3: runhcs.lm.DestinationResources.task_rootfs:type_name -> runhcs.lm.DestinationRootFS
	25, // 4: runhcs.lm.DestinationRootFS.rootfs:type_name -> containerd.types.Mount
	23, // 5: runhcs.lm.ContainerRestoreSpec.annotations:type_name -> runhcs.lm.ContainerRestoreSpec.AnnotationsEntry
	24, // 6: runhcs.lm.PrepareSandboxResponse.config:type_name -> google.protobuf.Any
	8,  // 7: runhcs.lm.PrepareSandboxResponse.resources:type_name -> runhcs.lm.SourceResources
	9,  // 8: runhcs.lm.SourceResources.task_rootfs:type_name -> runhcs.lm.SourceRootFS
	0,  // 9: runhcs.lm.TransferSandboxResponse.status:type_name -> runhcs.lm.TransferSandboxResponse.Status
	26, // 10: runhcs.lm.TransferSandboxResponse.start_time:type_name -> google.protobuf.Timestamp
	26, // 11: runhcs.lm.TransferSandboxResponse.update_time:type_name -> google.protobuf.Timestamp
	1,  // 12: runhcs.lm.FinalizeSandboxRequest.action:type_name -> runhcs.lm.FinalizeSandboxRequest.Action
	6,  // 13: runhcs.lm.Migration.PrepareSandbox:input_type -> runhcs.lm.PrepareSandboxRequest
	10, // 14: runhcs.lm.Migration.ListenChannel:input_type -> runhcs.lm.ListenChannelRequest
	12, // 15: runhcs.lm.Migration.AcceptChannel:input_type -> runhcs.lm.AcceptChannelRequest
	14, // 16: runhcs.lm.Migration.DialChannel:input_type -> runhcs.lm.DialChannelRequest
	16, // 17: runhcs.lm.Migration.TransferSandbox:input_type -> runhcs.lm.TransferSandboxRequest
	20, // 18: runhcs.lm.Migration.FinalizeSandbox:input_type -> runhcs.lm.FinalizeSandboxRequest
	18, // 19: runhcs.lm.Migration.Cancel:input_type -> runhcs.lm.CancelRequest
	7,  // 20: runhcs.lm.Migration.PrepareSandbox:output_type -> runhcs.lm.PrepareSandboxResponse
	11, // 21: runhcs.lm.Migration.ListenChannel:output_type -> runhcs.lm.ListenChannelResponse
	13, // 22: runhcs.lm.Migration.AcceptChannel:output_type -> runhcs.lm.AcceptChannelResponse
	15, // 23: runhcs.lm.Migration.DialChannel:output_type -> runhcs.lm.DialChannelResponse
	17, // 24: runhcs.lm.Migration.TransferSandbox:output_type -> runhcs.lm.TransferSandboxResponse
	21, // 25: runhcs.lm.Migration.FinalizeSandbox:output_type -> runhcs.lm.FinalizeSandboxResponse
	19, // 26: runhcs.lm.Migration.Cancel:output_type -> runhcs.lm.CancelResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_init() }
func file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_init() {
	if File_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandboxLMSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestinationResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestinationRootFS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerRestoreSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareSandboxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareSandboxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceRootFS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferSandboxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferSandboxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeSandboxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeSandboxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_goTypes,
		DependencyIndexes: file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_depIdxs,
		EnumInfos:         file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_enumTypes,
		MessageInfos:      file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_msgTypes,
	}.Build()
	File_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto = out.File
	file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_rawDesc = nil
	file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_goTypes = nil
	file_github_com_Microsoft_hcsshim_internal_lm_proto_lm_proto_depIdxs = nil
}
