// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: internal/lm/proto/lm.proto
package lmproto

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type MigrationService interface {
	PrepareSandbox(context.Context, *PrepareSandboxRequest) (*PrepareSandboxResponse, error)
	ListenChannel(context.Context, *ListenChannelRequest) (*ListenChannelResponse, error)
	AcceptChannel(context.Context, *AcceptChannelRequest) (*AcceptChannelResponse, error)
	DialChannel(context.Context, *DialChannelRequest) (*DialChannelResponse, error)
	TransferSandbox(context.Context, *TransferSandboxRequest, Migration_TransferSandboxServer) error
	FinalizeSandbox(context.Context, *FinalizeSandboxRequest) (*FinalizeSandboxResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	CreateDuplicateSocket(context.Context, *CreateDuplicateSocketRequest) (*CreateDuplicateSocketResponse, error)
	WaitForChannelReady(context.Context, *WaitForChannelReadyRequest) (*WaitForChannelReadyResponse, error)
}

type Migration_TransferSandboxServer interface {
	Send(*TransferSandboxResponse) error
	ttrpc.StreamServer
}

type migrationTransferSandboxServer struct {
	ttrpc.StreamServer
}

func (x *migrationTransferSandboxServer) Send(m *TransferSandboxResponse) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterMigrationService(srv *ttrpc.Server, svc MigrationService) {
	srv.RegisterService("runhcs.lm.Migration", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"PrepareSandbox": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req PrepareSandboxRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.PrepareSandbox(ctx, &req)
			},
			"ListenChannel": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ListenChannelRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ListenChannel(ctx, &req)
			},
			"AcceptChannel": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req AcceptChannelRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.AcceptChannel(ctx, &req)
			},
			"DialChannel": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req DialChannelRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.DialChannel(ctx, &req)
			},
			"FinalizeSandbox": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req FinalizeSandboxRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.FinalizeSandbox(ctx, &req)
			},
			"Cancel": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CancelRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Cancel(ctx, &req)
			},
			"CreateDuplicateSocket": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CreateDuplicateSocketRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.CreateDuplicateSocket(ctx, &req)
			},
			"WaitForChannelReady": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req WaitForChannelReadyRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.WaitForChannelReady(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"TransferSandbox": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(TransferSandboxRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.TransferSandbox(ctx, m, &migrationTransferSandboxServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type MigrationClient interface {
	PrepareSandbox(context.Context, *PrepareSandboxRequest) (*PrepareSandboxResponse, error)
	ListenChannel(context.Context, *ListenChannelRequest) (*ListenChannelResponse, error)
	AcceptChannel(context.Context, *AcceptChannelRequest) (*AcceptChannelResponse, error)
	DialChannel(context.Context, *DialChannelRequest) (*DialChannelResponse, error)
	TransferSandbox(context.Context, *TransferSandboxRequest) (Migration_TransferSandboxClient, error)
	FinalizeSandbox(context.Context, *FinalizeSandboxRequest) (*FinalizeSandboxResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	CreateDuplicateSocket(context.Context, *CreateDuplicateSocketRequest) (*CreateDuplicateSocketResponse, error)
	WaitForChannelReady(context.Context, *WaitForChannelReadyRequest) (*WaitForChannelReadyResponse, error)
}

type migrationClient struct {
	client *ttrpc.Client
}

func NewMigrationClient(client *ttrpc.Client) MigrationClient {
	return &migrationClient{
		client: client,
	}
}

func (c *migrationClient) PrepareSandbox(ctx context.Context, req *PrepareSandboxRequest) (*PrepareSandboxResponse, error) {
	var resp PrepareSandboxResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "PrepareSandbox", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *migrationClient) ListenChannel(ctx context.Context, req *ListenChannelRequest) (*ListenChannelResponse, error) {
	var resp ListenChannelResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "ListenChannel", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *migrationClient) AcceptChannel(ctx context.Context, req *AcceptChannelRequest) (*AcceptChannelResponse, error) {
	var resp AcceptChannelResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "AcceptChannel", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *migrationClient) DialChannel(ctx context.Context, req *DialChannelRequest) (*DialChannelResponse, error) {
	var resp DialChannelResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "DialChannel", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *migrationClient) TransferSandbox(ctx context.Context, req *TransferSandboxRequest) (Migration_TransferSandboxClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "runhcs.lm.Migration", "TransferSandbox", req)
	if err != nil {
		return nil, err
	}
	x := &migrationTransferSandboxClient{stream}
	return x, nil
}

type Migration_TransferSandboxClient interface {
	Recv() (*TransferSandboxResponse, error)
	ttrpc.ClientStream
}

type migrationTransferSandboxClient struct {
	ttrpc.ClientStream
}

func (x *migrationTransferSandboxClient) Recv() (*TransferSandboxResponse, error) {
	m := new(TransferSandboxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *migrationClient) FinalizeSandbox(ctx context.Context, req *FinalizeSandboxRequest) (*FinalizeSandboxResponse, error) {
	var resp FinalizeSandboxResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "FinalizeSandbox", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *migrationClient) Cancel(ctx context.Context, req *CancelRequest) (*CancelResponse, error) {
	var resp CancelResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "Cancel", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *migrationClient) CreateDuplicateSocket(ctx context.Context, req *CreateDuplicateSocketRequest) (*CreateDuplicateSocketResponse, error) {
	var resp CreateDuplicateSocketResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "CreateDuplicateSocket", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *migrationClient) WaitForChannelReady(ctx context.Context, req *WaitForChannelReadyRequest) (*WaitForChannelReadyResponse, error) {
	var resp WaitForChannelReadyResponse
	if err := c.client.Call(ctx, "runhcs.lm.Migration", "WaitForChannelReady", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
