//go:build windows

// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -build_constraint=windows -package=mock -destination=mock/mock_network.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	hcn "github.com/Microsoft/hcsshim/hcn"
	network "github.com/Microsoft/hcsshim/internal/controller/network"
	gcs "github.com/Microsoft/hcsshim/internal/gcs"
	hcsschema "github.com/Microsoft/hcsshim/internal/hcs/schema2"
	guestrequest "github.com/Microsoft/hcsshim/internal/protocol/guestrequest"
	guestresource "github.com/Microsoft/hcsshim/internal/protocol/guestresource"
	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Setup mocks base method.
func (m *MockController) Setup(ctx context.Context, opts *network.SetupOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setup", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup.
func (mr *MockControllerMockRecorder) Setup(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockController)(nil).Setup), ctx, opts)
}

// Teardown mocks base method.
func (m *MockController) Teardown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Teardown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Teardown indicates an expected call of Teardown.
func (mr *MockControllerMockRecorder) Teardown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Teardown", reflect.TypeOf((*MockController)(nil).Teardown), ctx)
}

// MockcapabilitiesProvider is a mock of capabilitiesProvider interface.
type MockcapabilitiesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockcapabilitiesProviderMockRecorder
	isgomock struct{}
}

// MockcapabilitiesProviderMockRecorder is the mock recorder for MockcapabilitiesProvider.
type MockcapabilitiesProviderMockRecorder struct {
	mock *MockcapabilitiesProvider
}

// NewMockcapabilitiesProvider creates a new mock instance.
func NewMockcapabilitiesProvider(ctrl *gomock.Controller) *MockcapabilitiesProvider {
	mock := &MockcapabilitiesProvider{ctrl: ctrl}
	mock.recorder = &MockcapabilitiesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcapabilitiesProvider) EXPECT() *MockcapabilitiesProviderMockRecorder {
	return m.recorder
}

// Capabilities mocks base method.
func (m *MockcapabilitiesProvider) Capabilities() gcs.GuestDefinedCapabilities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capabilities")
	ret0, _ := ret[0].(gcs.GuestDefinedCapabilities)
	return ret0
}

// Capabilities indicates an expected call of Capabilities.
func (mr *MockcapabilitiesProviderMockRecorder) Capabilities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capabilities", reflect.TypeOf((*MockcapabilitiesProvider)(nil).Capabilities))
}

// MockvmNetworkManager is a mock of vmNetworkManager interface.
type MockvmNetworkManager struct {
	ctrl     *gomock.Controller
	recorder *MockvmNetworkManagerMockRecorder
	isgomock struct{}
}

// MockvmNetworkManagerMockRecorder is the mock recorder for MockvmNetworkManager.
type MockvmNetworkManagerMockRecorder struct {
	mock *MockvmNetworkManager
}

// NewMockvmNetworkManager creates a new mock instance.
func NewMockvmNetworkManager(ctrl *gomock.Controller) *MockvmNetworkManager {
	mock := &MockvmNetworkManager{ctrl: ctrl}
	mock.recorder = &MockvmNetworkManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvmNetworkManager) EXPECT() *MockvmNetworkManagerMockRecorder {
	return m.recorder
}

// AddNIC mocks base method.
func (m *MockvmNetworkManager) AddNIC(ctx context.Context, nicID string, settings *hcsschema.NetworkAdapter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNIC", ctx, nicID, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNIC indicates an expected call of AddNIC.
func (mr *MockvmNetworkManagerMockRecorder) AddNIC(ctx, nicID, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNIC", reflect.TypeOf((*MockvmNetworkManager)(nil).AddNIC), ctx, nicID, settings)
}

// RemoveNIC mocks base method.
func (m *MockvmNetworkManager) RemoveNIC(ctx context.Context, nicID string, settings *hcsschema.NetworkAdapter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNIC", ctx, nicID, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNIC indicates an expected call of RemoveNIC.
func (mr *MockvmNetworkManagerMockRecorder) RemoveNIC(ctx, nicID, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNIC", reflect.TypeOf((*MockvmNetworkManager)(nil).RemoveNIC), ctx, nicID, settings)
}

// MocklinuxGuestNetworkManager is a mock of linuxGuestNetworkManager interface.
type MocklinuxGuestNetworkManager struct {
	ctrl     *gomock.Controller
	recorder *MocklinuxGuestNetworkManagerMockRecorder
	isgomock struct{}
}

// MocklinuxGuestNetworkManagerMockRecorder is the mock recorder for MocklinuxGuestNetworkManager.
type MocklinuxGuestNetworkManagerMockRecorder struct {
	mock *MocklinuxGuestNetworkManager
}

// NewMocklinuxGuestNetworkManager creates a new mock instance.
func NewMocklinuxGuestNetworkManager(ctrl *gomock.Controller) *MocklinuxGuestNetworkManager {
	mock := &MocklinuxGuestNetworkManager{ctrl: ctrl}
	mock.recorder = &MocklinuxGuestNetworkManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklinuxGuestNetworkManager) EXPECT() *MocklinuxGuestNetworkManagerMockRecorder {
	return m.recorder
}

// AddLCOWNetworkInterface mocks base method.
func (m *MocklinuxGuestNetworkManager) AddLCOWNetworkInterface(ctx context.Context, settings *guestresource.LCOWNetworkAdapter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLCOWNetworkInterface", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLCOWNetworkInterface indicates an expected call of AddLCOWNetworkInterface.
func (mr *MocklinuxGuestNetworkManagerMockRecorder) AddLCOWNetworkInterface(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLCOWNetworkInterface", reflect.TypeOf((*MocklinuxGuestNetworkManager)(nil).AddLCOWNetworkInterface), ctx, settings)
}

// RemoveLCOWNetworkInterface mocks base method.
func (m *MocklinuxGuestNetworkManager) RemoveLCOWNetworkInterface(ctx context.Context, settings *guestresource.LCOWNetworkAdapter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLCOWNetworkInterface", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLCOWNetworkInterface indicates an expected call of RemoveLCOWNetworkInterface.
func (mr *MocklinuxGuestNetworkManagerMockRecorder) RemoveLCOWNetworkInterface(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLCOWNetworkInterface", reflect.TypeOf((*MocklinuxGuestNetworkManager)(nil).RemoveLCOWNetworkInterface), ctx, settings)
}

// MockwindowsGuestNetworkManager is a mock of windowsGuestNetworkManager interface.
type MockwindowsGuestNetworkManager struct {
	ctrl     *gomock.Controller
	recorder *MockwindowsGuestNetworkManagerMockRecorder
	isgomock struct{}
}

// MockwindowsGuestNetworkManagerMockRecorder is the mock recorder for MockwindowsGuestNetworkManager.
type MockwindowsGuestNetworkManagerMockRecorder struct {
	mock *MockwindowsGuestNetworkManager
}

// NewMockwindowsGuestNetworkManager creates a new mock instance.
func NewMockwindowsGuestNetworkManager(ctrl *gomock.Controller) *MockwindowsGuestNetworkManager {
	mock := &MockwindowsGuestNetworkManager{ctrl: ctrl}
	mock.recorder = &MockwindowsGuestNetworkManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwindowsGuestNetworkManager) EXPECT() *MockwindowsGuestNetworkManagerMockRecorder {
	return m.recorder
}

// AddNetworkInterface mocks base method.
func (m *MockwindowsGuestNetworkManager) AddNetworkInterface(ctx context.Context, adapterID string, requestType guestrequest.RequestType, settings *hcn.HostComputeEndpoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNetworkInterface", ctx, adapterID, requestType, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNetworkInterface indicates an expected call of AddNetworkInterface.
func (mr *MockwindowsGuestNetworkManagerMockRecorder) AddNetworkInterface(ctx, adapterID, requestType, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNetworkInterface", reflect.TypeOf((*MockwindowsGuestNetworkManager)(nil).AddNetworkInterface), ctx, adapterID, requestType, settings)
}

// AddNetworkNamespace mocks base method.
func (m *MockwindowsGuestNetworkManager) AddNetworkNamespace(ctx context.Context, settings *hcn.HostComputeNamespace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNetworkNamespace", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNetworkNamespace indicates an expected call of AddNetworkNamespace.
func (mr *MockwindowsGuestNetworkManagerMockRecorder) AddNetworkNamespace(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNetworkNamespace", reflect.TypeOf((*MockwindowsGuestNetworkManager)(nil).AddNetworkNamespace), ctx, settings)
}

// RemoveNetworkInterface mocks base method.
func (m *MockwindowsGuestNetworkManager) RemoveNetworkInterface(ctx context.Context, adapterID string, requestType guestrequest.RequestType, settings *hcn.HostComputeEndpoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNetworkInterface", ctx, adapterID, requestType, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNetworkInterface indicates an expected call of RemoveNetworkInterface.
func (mr *MockwindowsGuestNetworkManagerMockRecorder) RemoveNetworkInterface(ctx, adapterID, requestType, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNetworkInterface", reflect.TypeOf((*MockwindowsGuestNetworkManager)(nil).RemoveNetworkInterface), ctx, adapterID, requestType, settings)
}

// RemoveNetworkNamespace mocks base method.
func (m *MockwindowsGuestNetworkManager) RemoveNetworkNamespace(ctx context.Context, settings *hcn.HostComputeNamespace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNetworkNamespace", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNetworkNamespace indicates an expected call of RemoveNetworkNamespace.
func (mr *MockwindowsGuestNetworkManagerMockRecorder) RemoveNetworkNamespace(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNetworkNamespace", reflect.TypeOf((*MockwindowsGuestNetworkManager)(nil).RemoveNetworkNamespace), ctx, settings)
}
