// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: github.com/Microsoft/hcsshim/internal/state/state.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SCSIAttachment_AttachmentType int32

const (
	SCSIAttachment_VirtualDisk           SCSIAttachment_AttachmentType = 0
	SCSIAttachment_PassThru              SCSIAttachment_AttachmentType = 1
	SCSIAttachment_ExtensibleVirtualDisk SCSIAttachment_AttachmentType = 2
)

// Enum value maps for SCSIAttachment_AttachmentType.
var (
	SCSIAttachment_AttachmentType_name = map[int32]string{
		0: "VirtualDisk",
		1: "PassThru",
		2: "ExtensibleVirtualDisk",
	}
	SCSIAttachment_AttachmentType_value = map[string]int32{
		"VirtualDisk":           0,
		"PassThru":              1,
		"ExtensibleVirtualDisk": 2,
	}
)

func (x SCSIAttachment_AttachmentType) Enum() *SCSIAttachment_AttachmentType {
	p := new(SCSIAttachment_AttachmentType)
	*p = x
	return p
}

func (x SCSIAttachment_AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SCSIAttachment_AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_enumTypes[0].Descriptor()
}

func (SCSIAttachment_AttachmentType) Type() protoreflect.EnumType {
	return &file_github_com_Microsoft_hcsshim_internal_state_state_proto_enumTypes[0]
}

func (x SCSIAttachment_AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SCSIAttachment_AttachmentType.Descriptor instead.
func (SCSIAttachment_AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{6, 0}
}

type TaskServerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sandbox *SandboxState         `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Tasks   map[string]*TaskState `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TaskServerState) Reset() {
	*x = TaskServerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServerState) ProtoMessage() {}

func (x *TaskServerState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServerState.ProtoReflect.Descriptor instead.
func (*TaskServerState) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{0}
}

func (x *TaskServerState) GetSandbox() *SandboxState {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *TaskServerState) GetTasks() map[string]*TaskState {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SandboxState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vm    *VMState `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Agent *GCState `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *SandboxState) Reset() {
	*x = SandboxState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxState) ProtoMessage() {}

func (x *SandboxState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxState.ProtoReflect.Descriptor instead.
func (*SandboxState) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxState) GetVm() *VMState {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *SandboxState) GetAgent() *GCState {
	if x != nil {
		return x.Agent
	}
	return nil
}

type VMState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config     *VMConfig   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	CompatInfo []byte      `protobuf:"bytes,2,opt,name=compat_info,json=compatInfo,proto3" json:"compat_info,omitempty"`
	Resources  []*Resource `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *VMState) Reset() {
	*x = VMState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMState) ProtoMessage() {}

func (x *VMState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMState.ProtoReflect.Descriptor instead.
func (*VMState) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{2}
}

func (x *VMState) GetConfig() *VMConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *VMState) GetCompatInfo() []byte {
	if x != nil {
		return x.CompatInfo
	}
	return nil
}

func (x *VMState) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type VMConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpCount    int32                      `protobuf:"varint,1,opt,name=vp_count,json=vpCount,proto3" json:"vp_count,omitempty"`
	MemCountMb uint64                     `protobuf:"varint,2,opt,name=mem_count_mb,json=memCountMb,proto3" json:"mem_count_mb,omitempty"`
	VaBacked   bool                       `protobuf:"varint,3,opt,name=va_backed,json=vaBacked,proto3" json:"va_backed,omitempty"`
	Scsi       map[uint32]*SCSIController `protobuf:"bytes,4,rep,name=scsi,proto3" json:"scsi,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Nics       map[string]*NIC            `protobuf:"bytes,5,rep,name=nics,proto3" json:"nics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *VMConfig) Reset() {
	*x = VMConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMConfig) ProtoMessage() {}

func (x *VMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMConfig.ProtoReflect.Descriptor instead.
func (*VMConfig) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{3}
}

func (x *VMConfig) GetVpCount() int32 {
	if x != nil {
		return x.VpCount
	}
	return 0
}

func (x *VMConfig) GetMemCountMb() uint64 {
	if x != nil {
		return x.MemCountMb
	}
	return 0
}

func (x *VMConfig) GetVaBacked() bool {
	if x != nil {
		return x.VaBacked
	}
	return false
}

func (x *VMConfig) GetScsi() map[uint32]*SCSIController {
	if x != nil {
		return x.Scsi
	}
	return nil
}

func (x *VMConfig) GetNics() map[string]*NIC {
	if x != nil {
		return x.Nics
	}
	return nil
}

type NIC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndpointId string `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	MacAddress string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
}

func (x *NIC) Reset() {
	*x = NIC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NIC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NIC) ProtoMessage() {}

func (x *NIC) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NIC.ProtoReflect.Descriptor instead.
func (*NIC) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{4}
}

func (x *NIC) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *NIC) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type SCSIController struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attachments map[uint32]*SCSIAttachment `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SCSIController) Reset() {
	*x = SCSIController{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCSIController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCSIController) ProtoMessage() {}

func (x *SCSIController) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCSIController.ProtoReflect.Descriptor instead.
func (*SCSIController) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{5}
}

func (x *SCSIController) GetAttachments() map[uint32]*SCSIAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type SCSIAttachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     SCSIAttachment_AttachmentType `protobuf:"varint,1,opt,name=type,proto3,enum=containerd.runhcs.v1.state.SCSIAttachment_AttachmentType" json:"type,omitempty"`
	Path     string                        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ReadOnly bool                          `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	EvdType  string                        `protobuf:"bytes,4,opt,name=evd_type,json=evdType,proto3" json:"evd_type,omitempty"`
}

func (x *SCSIAttachment) Reset() {
	*x = SCSIAttachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCSIAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCSIAttachment) ProtoMessage() {}

func (x *SCSIAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCSIAttachment.ProtoReflect.Descriptor instead.
func (*SCSIAttachment) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{6}
}

func (x *SCSIAttachment) GetType() SCSIAttachment_AttachmentType {
	if x != nil {
		return x.Type
	}
	return SCSIAttachment_VirtualDisk
}

func (x *SCSIAttachment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SCSIAttachment) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *SCSIAttachment) GetEvdType() string {
	if x != nil {
		return x.EvdType
	}
	return ""
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Resource_Layers_
	Type isResource_Type `protobuf_oneof:"type"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{7}
}

func (m *Resource) GetType() isResource_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Resource) GetLayers() *Resource_Layers {
	if x, ok := x.GetType().(*Resource_Layers_); ok {
		return x.Layers
	}
	return nil
}

type isResource_Type interface {
	isResource_Type()
}

type Resource_Layers_ struct {
	Layers *Resource_Layers `protobuf:"bytes,1,opt,name=layers,proto3,oneof"`
}

func (*Resource_Layers_) isResource_Type() {}

type GuestState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuestState) Reset() {
	*x = GuestState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestState) ProtoMessage() {}

func (x *GuestState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestState.ProtoReflect.Descriptor instead.
func (*GuestState) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{8}
}

type GuestStateDisconnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *GuestState `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *GuestStateDisconnected) Reset() {
	*x = GuestStateDisconnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestStateDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestStateDisconnected) ProtoMessage() {}

func (x *GuestStateDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestStateDisconnected.ProtoReflect.Descriptor instead.
func (*GuestStateDisconnected) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{9}
}

func (x *GuestStateDisconnected) GetCommon() *GuestState {
	if x != nil {
		return x.Common
	}
	return nil
}

type GuestStateConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *GuestState `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *GuestStateConnected) Reset() {
	*x = GuestStateConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestStateConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestStateConnected) ProtoMessage() {}

func (x *GuestStateConnected) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestStateConnected.ProtoReflect.Descriptor instead.
func (*GuestStateConnected) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{10}
}

func (x *GuestStateConnected) GetCommon() *GuestState {
	if x != nil {
		return x.Common
	}
	return nil
}

type GCState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processes []*Process `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	NextPort  uint32     `protobuf:"varint,2,opt,name=next_port,json=nextPort,proto3" json:"next_port,omitempty"`
}

func (x *GCState) Reset() {
	*x = GCState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCState) ProtoMessage() {}

func (x *GCState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCState.ProtoReflect.Descriptor instead.
func (*GCState) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{11}
}

func (x *GCState) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *GCState) GetNextPort() uint32 {
	if x != nil {
		return x.NextPort
	}
	return 0
}

type Process struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ProcessId   uint32 `protobuf:"varint,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	StdinPort   uint32 `protobuf:"varint,3,opt,name=stdin_port,json=stdinPort,proto3" json:"stdin_port,omitempty"`
	StdoutPort  uint32 `protobuf:"varint,4,opt,name=stdout_port,json=stdoutPort,proto3" json:"stdout_port,omitempty"`
	StderrPort  uint32 `protobuf:"varint,5,opt,name=stderr_port,json=stderrPort,proto3" json:"stderr_port,omitempty"`
}

func (x *Process) Reset() {
	*x = Process{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{12}
}

func (x *Process) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Process) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Process) GetStdinPort() uint32 {
	if x != nil {
		return x.StdinPort
	}
	return 0
}

func (x *Process) GetStdoutPort() uint32 {
	if x != nil {
		return x.StdoutPort
	}
	return 0
}

func (x *Process) GetStderrPort() uint32 {
	if x != nil {
		return x.StderrPort
	}
	return 0
}

type TaskState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecId   string `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Terminal bool   `protobuf:"varint,3,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Pid      uint32 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *TaskState) Reset() {
	*x = TaskState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskState) ProtoMessage() {}

func (x *TaskState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskState.ProtoReflect.Descriptor instead.
func (*TaskState) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{13}
}

func (x *TaskState) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskState) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *TaskState) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *TaskState) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type Resource_Layers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId         string                  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Scratch        *Resource_Layers_SCSI   `protobuf:"bytes,2,opt,name=Scratch,proto3" json:"Scratch,omitempty"`
	ReadOnlyLayers []*Resource_Layers_SCSI `protobuf:"bytes,3,rep,name=ReadOnlyLayers,proto3" json:"ReadOnlyLayers,omitempty"`
}

func (x *Resource_Layers) Reset() {
	*x = Resource_Layers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource_Layers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource_Layers) ProtoMessage() {}

func (x *Resource_Layers) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource_Layers.ProtoReflect.Descriptor instead.
func (*Resource_Layers) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Resource_Layers) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Resource_Layers) GetScratch() *Resource_Layers_SCSI {
	if x != nil {
		return x.Scratch
	}
	return nil
}

func (x *Resource_Layers) GetReadOnlyLayers() []*Resource_Layers_SCSI {
	if x != nil {
		return x.ReadOnlyLayers
	}
	return nil
}

type Resource_Layers_SCSI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Controller uint32 `protobuf:"varint,1,opt,name=controller,proto3" json:"controller,omitempty"`
	Lun        uint32 `protobuf:"varint,2,opt,name=lun,proto3" json:"lun,omitempty"`
}

func (x *Resource_Layers_SCSI) Reset() {
	*x = Resource_Layers_SCSI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource_Layers_SCSI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource_Layers_SCSI) ProtoMessage() {}

func (x *Resource_Layers_SCSI) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource_Layers_SCSI.ProtoReflect.Descriptor instead.
func (*Resource_Layers_SCSI) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP(), []int{7, 0, 0}
}

func (x *Resource_Layers_SCSI) GetController() uint32 {
	if x != nil {
		return x.Controller
	}
	return 0
}

func (x *Resource_Layers_SCSI) GetLun() uint32 {
	if x != nil {
		return x.Lun
	}
	return 0
}

var File_github_com_Microsoft_hcsshim_internal_state_state_proto protoreflect.FileDescriptor

var file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDesc = []byte{
	0x0a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x68, 0x63, 0x73, 0x73, 0x68, 0x69, 0x6d, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x84, 0x02, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x12, 0x4c, 0x0a,
	0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x1a, 0x5f, 0x0a, 0x0a, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3b, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x7e, 0x0a, 0x0c,
	0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x02,
	0x76, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x02, 0x76,
	0x6d, 0x12, 0x39, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75,
	0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x43,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xac, 0x01, 0x0a,
	0x07, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x4d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0xab, 0x03, 0x0a, 0x08,
	0x56, 0x4d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x70, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x70, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x6d, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x4d, 0x62, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x61, 0x5f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x61, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x12, 0x42, 0x0a, 0x04, 0x73, 0x63, 0x73, 0x69, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75,
	0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x4d,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x73, 0x69, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x04, 0x73, 0x63, 0x73, 0x69, 0x12, 0x42, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x56, 0x4d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4e, 0x69, 0x63, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x73, 0x1a, 0x63, 0x0a, 0x09, 0x53, 0x63,
	0x73, 0x69, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x40, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x43, 0x53, 0x49, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x58, 0x0a, 0x09, 0x4e, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x4e, 0x49, 0x43, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x47, 0x0a, 0x03, 0x4e, 0x49, 0x43,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0xdb, 0x01, 0x0a, 0x0e, 0x53, 0x43, 0x53, 0x49, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x5d, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x43, 0x53, 0x49, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x1a, 0x6a, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x40, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x43, 0x53, 0x49, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xf7, 0x01, 0x0a, 0x0e, 0x53, 0x43, 0x53, 0x49, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x4d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x39, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72,
	0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53,
	0x43, 0x53, 0x49, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6f,
	0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x4f,
	0x6e, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4a,
	0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x54, 0x68, 0x72, 0x75, 0x10, 0x01, 0x12,
	0x19, 0x0a, 0x15, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x10, 0x02, 0x22, 0xdd, 0x02, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x81,
	0x02, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x4a, 0x0a, 0x07, 0x53, 0x63, 0x72, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64,
	0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x2e, 0x53, 0x43, 0x53, 0x49, 0x52, 0x07, 0x53, 0x63, 0x72, 0x61, 0x74, 0x63, 0x68, 0x12, 0x58,
	0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x2e, 0x53, 0x43, 0x53, 0x49, 0x52, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e,
	0x6c, 0x79, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x38, 0x0a, 0x04, 0x53, 0x43, 0x53, 0x49,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x75, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6c,
	0x75, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x58, 0x0a, 0x16, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x12, 0x3e, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x47, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x13, 0x47, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x69, 0x0a, 0x07, 0x47, 0x43, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74,
	0x50, 0x6f, 0x72, 0x74, 0x22, 0xac, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x22, 0x6b, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x78, 0x65,
	0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x65, 0x63,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x68, 0x63, 0x73, 0x73, 0x68, 0x69, 0x6d,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x3b,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescOnce sync.Once
	file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescData = file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDesc
)

func file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescGZIP() []byte {
	file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescOnce.Do(func() {
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescData)
	})
	return file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDescData
}

var file_github_com_Microsoft_hcsshim_internal_state_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_github_com_Microsoft_hcsshim_internal_state_state_proto_goTypes = []interface{}{
	(SCSIAttachment_AttachmentType)(0), // 0: containerd.runhcs.v1.state.SCSIAttachment.AttachmentType
	(*TaskServerState)(nil),            // 1: containerd.runhcs.v1.state.TaskServerState
	(*SandboxState)(nil),               // 2: containerd.runhcs.v1.state.SandboxState
	(*VMState)(nil),                    // 3: containerd.runhcs.v1.state.VMState
	(*VMConfig)(nil),                   // 4: containerd.runhcs.v1.state.VMConfig
	(*NIC)(nil),                        // 5: containerd.runhcs.v1.state.NIC
	(*SCSIController)(nil),             // 6: containerd.runhcs.v1.state.SCSIController
	(*SCSIAttachment)(nil),             // 7: containerd.runhcs.v1.state.SCSIAttachment
	(*Resource)(nil),                   // 8: containerd.runhcs.v1.state.Resource
	(*GuestState)(nil),                 // 9: containerd.runhcs.v1.state.GuestState
	(*GuestStateDisconnected)(nil),     // 10: containerd.runhcs.v1.state.GuestStateDisconnected
	(*GuestStateConnected)(nil),        // 11: containerd.runhcs.v1.state.GuestStateConnected
	(*GCState)(nil),                    // 12: containerd.runhcs.v1.state.GCState
	(*Process)(nil),                    // 13: containerd.runhcs.v1.state.Process
	(*TaskState)(nil),                  // 14: containerd.runhcs.v1.state.TaskState
	nil,                                // 15: containerd.runhcs.v1.state.TaskServerState.TasksEntry
	nil,                                // 16: containerd.runhcs.v1.state.VMConfig.ScsiEntry
	nil,                                // 17: containerd.runhcs.v1.state.VMConfig.NicsEntry
	nil,                                // 18: containerd.runhcs.v1.state.SCSIController.AttachmentsEntry
	(*Resource_Layers)(nil),            // 19: containerd.runhcs.v1.state.Resource.Layers
	(*Resource_Layers_SCSI)(nil),       // 20: containerd.runhcs.v1.state.Resource.Layers.SCSI
}
var file_github_com_Microsoft_hcsshim_internal_state_state_proto_depIdxs = []int32{
	2,  // 0: containerd.runhcs.v1.state.TaskServerState.sandbox:type_name -> containerd.runhcs.v1.state.SandboxState
	15, // 1: containerd.runhcs.v1.state.TaskServerState.tasks:type_name -> containerd.runhcs.v1.state.TaskServerState.TasksEntry
	3,  // 2: containerd.runhcs.v1.state.SandboxState.vm:type_name -> containerd.runhcs.v1.state.VMState
	12, // 3: containerd.runhcs.v1.state.SandboxState.agent:type_name -> containerd.runhcs.v1.state.GCState
	4,  // 4: containerd.runhcs.v1.state.VMState.config:type_name -> containerd.runhcs.v1.state.VMConfig
	8,  // 5: containerd.runhcs.v1.state.VMState.resources:type_name -> containerd.runhcs.v1.state.Resource
	16, // 6: containerd.runhcs.v1.state.VMConfig.scsi:type_name -> containerd.runhcs.v1.state.VMConfig.ScsiEntry
	17, // 7: containerd.runhcs.v1.state.VMConfig.nics:type_name -> containerd.runhcs.v1.state.VMConfig.NicsEntry
	18, // 8: containerd.runhcs.v1.state.SCSIController.attachments:type_name -> containerd.runhcs.v1.state.SCSIController.AttachmentsEntry
	0,  // 9: containerd.runhcs.v1.state.SCSIAttachment.type:type_name -> containerd.runhcs.v1.state.SCSIAttachment.AttachmentType
	19, // 10: containerd.runhcs.v1.state.Resource.layers:type_name -> containerd.runhcs.v1.state.Resource.Layers
	9,  // 11: containerd.runhcs.v1.state.GuestStateDisconnected.common:type_name -> containerd.runhcs.v1.state.GuestState
	9,  // 12: containerd.runhcs.v1.state.GuestStateConnected.common:type_name -> containerd.runhcs.v1.state.GuestState
	13, // 13: containerd.runhcs.v1.state.GCState.processes:type_name -> containerd.runhcs.v1.state.Process
	14, // 14: containerd.runhcs.v1.state.TaskServerState.TasksEntry.value:type_name -> containerd.runhcs.v1.state.TaskState
	6,  // 15: containerd.runhcs.v1.state.VMConfig.ScsiEntry.value:type_name -> containerd.runhcs.v1.state.SCSIController
	5,  // 16: containerd.runhcs.v1.state.VMConfig.NicsEntry.value:type_name -> containerd.runhcs.v1.state.NIC
	7,  // 17: containerd.runhcs.v1.state.SCSIController.AttachmentsEntry.value:type_name -> containerd.runhcs.v1.state.SCSIAttachment
	20, // 18: containerd.runhcs.v1.state.Resource.Layers.Scratch:type_name -> containerd.runhcs.v1.state.Resource.Layers.SCSI
	20, // 19: containerd.runhcs.v1.state.Resource.Layers.ReadOnlyLayers:type_name -> containerd.runhcs.v1.state.Resource.Layers.SCSI
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_github_com_Microsoft_hcsshim_internal_state_state_proto_init() }
func file_github_com_Microsoft_hcsshim_internal_state_state_proto_init() {
	if File_github_com_Microsoft_hcsshim_internal_state_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskServerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandboxState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NIC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCSIController); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCSIAttachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestStateDisconnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestStateConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Process); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource_Layers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource_Layers_SCSI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Resource_Layers_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Microsoft_hcsshim_internal_state_state_proto_goTypes,
		DependencyIndexes: file_github_com_Microsoft_hcsshim_internal_state_state_proto_depIdxs,
		EnumInfos:         file_github_com_Microsoft_hcsshim_internal_state_state_proto_enumTypes,
		MessageInfos:      file_github_com_Microsoft_hcsshim_internal_state_state_proto_msgTypes,
	}.Build()
	File_github_com_Microsoft_hcsshim_internal_state_state_proto = out.File
	file_github_com_Microsoft_hcsshim_internal_state_state_proto_rawDesc = nil
	file_github_com_Microsoft_hcsshim_internal_state_state_proto_goTypes = nil
	file_github_com_Microsoft_hcsshim_internal_state_state_proto_depIdxs = nil
}
