//go:build windows

// Code generated by MockGen. DO NOT EDIT.
// Source: guestcaps.go
//
// Generated by this command:
//
//	mockgen -source=guestcaps.go -build_constraint=windows -package=mock -destination=mock/mock_guestcaps.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGuestDefinedCapabilities is a mock of GuestDefinedCapabilities interface.
type MockGuestDefinedCapabilities struct {
	ctrl     *gomock.Controller
	recorder *MockGuestDefinedCapabilitiesMockRecorder
	isgomock struct{}
}

// MockGuestDefinedCapabilitiesMockRecorder is the mock recorder for MockGuestDefinedCapabilities.
type MockGuestDefinedCapabilitiesMockRecorder struct {
	mock *MockGuestDefinedCapabilities
}

// NewMockGuestDefinedCapabilities creates a new mock instance.
func NewMockGuestDefinedCapabilities(ctrl *gomock.Controller) *MockGuestDefinedCapabilities {
	mock := &MockGuestDefinedCapabilities{ctrl: ctrl}
	mock.recorder = &MockGuestDefinedCapabilitiesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestDefinedCapabilities) EXPECT() *MockGuestDefinedCapabilitiesMockRecorder {
	return m.recorder
}

// IsDeleteContainerStateSupported mocks base method.
func (m *MockGuestDefinedCapabilities) IsDeleteContainerStateSupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDeleteContainerStateSupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDeleteContainerStateSupported indicates an expected call of IsDeleteContainerStateSupported.
func (mr *MockGuestDefinedCapabilitiesMockRecorder) IsDeleteContainerStateSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDeleteContainerStateSupported", reflect.TypeOf((*MockGuestDefinedCapabilities)(nil).IsDeleteContainerStateSupported))
}

// IsDumpStacksSupported mocks base method.
func (m *MockGuestDefinedCapabilities) IsDumpStacksSupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDumpStacksSupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDumpStacksSupported indicates an expected call of IsDumpStacksSupported.
func (mr *MockGuestDefinedCapabilitiesMockRecorder) IsDumpStacksSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDumpStacksSupported", reflect.TypeOf((*MockGuestDefinedCapabilities)(nil).IsDumpStacksSupported))
}

// IsNamespaceAddRequestSupported mocks base method.
func (m *MockGuestDefinedCapabilities) IsNamespaceAddRequestSupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNamespaceAddRequestSupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNamespaceAddRequestSupported indicates an expected call of IsNamespaceAddRequestSupported.
func (mr *MockGuestDefinedCapabilitiesMockRecorder) IsNamespaceAddRequestSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNamespaceAddRequestSupported", reflect.TypeOf((*MockGuestDefinedCapabilities)(nil).IsNamespaceAddRequestSupported))
}

// IsSignalProcessSupported mocks base method.
func (m *MockGuestDefinedCapabilities) IsSignalProcessSupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSignalProcessSupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSignalProcessSupported indicates an expected call of IsSignalProcessSupported.
func (mr *MockGuestDefinedCapabilitiesMockRecorder) IsSignalProcessSupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSignalProcessSupported", reflect.TypeOf((*MockGuestDefinedCapabilities)(nil).IsSignalProcessSupported))
}
