// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.26.0
// source: github.com/Microsoft/hcsshim/pkg/shim/options/runhcs.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options_DebugType int32

const (
	Options_NPIPE Options_DebugType = 0
	Options_FILE  Options_DebugType = 1
	Options_ETW   Options_DebugType = 2
)

// Enum value maps for Options_DebugType.
var (
	Options_DebugType_name = map[int32]string{
		0: "NPIPE",
		1: "FILE",
		2: "ETW",
	}
	Options_DebugType_value = map[string]int32{
		"NPIPE": 0,
		"FILE":  1,
		"ETW":   2,
	}
)

func (x Options_DebugType) Enum() *Options_DebugType {
	p := new(Options_DebugType)
	*p = x
	return p
}

func (x Options_DebugType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Options_DebugType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_enumTypes[0].Descriptor()
}

func (Options_DebugType) Type() protoreflect.EnumType {
	return &file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_enumTypes[0]
}

func (x Options_DebugType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Options_DebugType.Descriptor instead.
func (Options_DebugType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescGZIP(), []int{0, 0}
}

// Options are the set of customizations that can be passed to the shim.
type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// debug tracing output type
	DebugType Options_DebugType `protobuf:"varint,1,opt,name=debug_type,json=debugType,proto3,enum=containerd.runhcs.v2.Options_DebugType" json:"debug_type,omitempty"`
	// log_level specifies the logrus log level for the shim. Supported values are a string representation of the
	// logrus log levels: "trace", "debug", "info", "warn", "error", "fatal", "panic".
	LogLevel string `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	// scrub_logs enables removing environment variables and other potentially sensitive information from logs.
	ScrubLogs     bool `protobuf:"varint,3,opt,name=scrub_logs,json=scrubLogs,proto3" json:"scrub_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetDebugType() Options_DebugType {
	if x != nil {
		return x.DebugType
	}
	return Options_NPIPE
}

func (x *Options) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Options) GetScrubLogs() bool {
	if x != nil {
		return x.ScrubLogs
	}
	return false
}

// ProcessDetails contains additional information about a process. This is the additional
// info returned in the Pids query.
type ProcessDetails struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ImageName                    string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	CreatedAt                    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	KernelTime_100Ns             uint64                 `protobuf:"varint,3,opt,name=kernel_time_100_ns,json=kernelTime100Ns,proto3" json:"kernel_time_100_ns,omitempty"`
	MemoryCommitBytes            uint64                 `protobuf:"varint,4,opt,name=memory_commit_bytes,json=memoryCommitBytes,proto3" json:"memory_commit_bytes,omitempty"`
	MemoryWorkingSetPrivateBytes uint64                 `protobuf:"varint,5,opt,name=memory_working_set_private_bytes,json=memoryWorkingSetPrivateBytes,proto3" json:"memory_working_set_private_bytes,omitempty"`
	MemoryWorkingSetSharedBytes  uint64                 `protobuf:"varint,6,opt,name=memory_working_set_shared_bytes,json=memoryWorkingSetSharedBytes,proto3" json:"memory_working_set_shared_bytes,omitempty"`
	ProcessID                    uint32                 `protobuf:"varint,7,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	UserTime_100Ns               uint64                 `protobuf:"varint,8,opt,name=user_time_100_ns,json=userTime100Ns,proto3" json:"user_time_100_ns,omitempty"`
	ExecID                       string                 `protobuf:"bytes,9,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ProcessDetails) Reset() {
	*x = ProcessDetails{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDetails) ProtoMessage() {}

func (x *ProcessDetails) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDetails.ProtoReflect.Descriptor instead.
func (*ProcessDetails) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessDetails) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ProcessDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProcessDetails) GetKernelTime_100Ns() uint64 {
	if x != nil {
		return x.KernelTime_100Ns
	}
	return 0
}

func (x *ProcessDetails) GetMemoryCommitBytes() uint64 {
	if x != nil {
		return x.MemoryCommitBytes
	}
	return 0
}

func (x *ProcessDetails) GetMemoryWorkingSetPrivateBytes() uint64 {
	if x != nil {
		return x.MemoryWorkingSetPrivateBytes
	}
	return 0
}

func (x *ProcessDetails) GetMemoryWorkingSetSharedBytes() uint64 {
	if x != nil {
		return x.MemoryWorkingSetSharedBytes
	}
	return 0
}

func (x *ProcessDetails) GetProcessID() uint32 {
	if x != nil {
		return x.ProcessID
	}
	return 0
}

func (x *ProcessDetails) GetUserTime_100Ns() uint64 {
	if x != nil {
		return x.UserTime_100Ns
	}
	return 0
}

func (x *ProcessDetails) GetExecID() string {
	if x != nil {
		return x.ExecID
	}
	return ""
}

var File_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto protoreflect.FileDescriptor

const file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDesc = "" +
	"\n" +
	":github.com/Microsoft/hcsshim/pkg/shim/options/runhcs.proto\x12\x14containerd.runhcs.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\aOptions\x12F\n" +
	"\n" +
	"debug_type\x18\x01 \x01(\x0e2'.containerd.runhcs.v2.Options.DebugTypeR\tdebugType\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x12\x1d\n" +
	"\n" +
	"scrub_logs\x18\x03 \x01(\bR\tscrubLogs\")\n" +
	"\tDebugType\x12\t\n" +
	"\x05NPIPE\x10\x00\x12\b\n" +
	"\x04FILE\x10\x01\x12\a\n" +
	"\x03ETW\x10\x02\"\xb6\x03\n" +
	"\x0eProcessDetails\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x12kernel_time_100_ns\x18\x03 \x01(\x04R\x0fkernelTime100Ns\x12.\n" +
	"\x13memory_commit_bytes\x18\x04 \x01(\x04R\x11memoryCommitBytes\x12F\n" +
	" memory_working_set_private_bytes\x18\x05 \x01(\x04R\x1cmemoryWorkingSetPrivateBytes\x12D\n" +
	"\x1fmemory_working_set_shared_bytes\x18\x06 \x01(\x04R\x1bmemoryWorkingSetSharedBytes\x12\x1d\n" +
	"\n" +
	"process_id\x18\a \x01(\rR\tprocessId\x12'\n" +
	"\x10user_time_100_ns\x18\b \x01(\x04R\ruserTime100Ns\x12\x17\n" +
	"\aexec_id\x18\t \x01(\tR\x06execIdB/Z-github.com/Microsoft/hcsshim/pkg/shim/optionsb\x06proto3"

var (
	file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescOnce sync.Once
	file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescData []byte
)

func file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescGZIP() []byte {
	file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescOnce.Do(func() {
		file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDesc)))
	})
	return file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDescData
}

var file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_goTypes = []any{
	(Options_DebugType)(0),        // 0: containerd.runhcs.v2.Options.DebugType
	(*Options)(nil),               // 1: containerd.runhcs.v2.Options
	(*ProcessDetails)(nil),        // 2: containerd.runhcs.v2.ProcessDetails
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_depIdxs = []int32{
	0, // 0: containerd.runhcs.v2.Options.debug_type:type_name -> containerd.runhcs.v2.Options.DebugType
	3, // 1: containerd.runhcs.v2.ProcessDetails.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_init() }
func file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_init() {
	if File_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_goTypes,
		DependencyIndexes: file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_depIdxs,
		EnumInfos:         file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_enumTypes,
		MessageInfos:      file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_msgTypes,
	}.Build()
	File_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto = out.File
	file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_goTypes = nil
	file_github_com_Microsoft_hcsshim_pkg_shim_options_runhcs_proto_depIdxs = nil
}
